# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: '3'
includes:
  gen:
    taskfile: ./taskfile-generated.yml
    internal: true
tasks:
  build_rust:
    desc: Build Rust project and package release tarball (requires PROJECT_NAME)
    cmds:
      - task: gen:build_rust.sh
        vars:
          PROJECT_NAME: '{{.PROJECT_NAME}}'
    requires:
      vars: [PROJECT_NAME]
