#!/usr/bin/env bash
# Generates taskfile/taskfile-generated.yml from taskfile/scripts/*.sh.
# Each script becomes one internal task named by its full filename, with the body embedded verbatim (shebang stripped) under singular `cmd:`.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
SOURCE_DIR="${REPO_ROOT}/taskfile/scripts"
OUTPUT_FILE="${REPO_ROOT}/taskfile/taskfile-generated.yml"

CHECK_MODE=false

usage() {
	echo "Usage: $(basename "$0") [--check]" >&2
	echo "  (no args)  regenerate ${OUTPUT_FILE#"$REPO_ROOT"/}" >&2
	echo "  --check    exit 1 if generated file is stale (no write)" >&2
}

while [[ $# -gt 0 ]]; do
	case "$1" in
	--check)
		CHECK_MODE=true
		shift
		;;
	-h | --help)
		usage
		exit 0
		;;
	*)
		echo "Unknown argument: $1" >&2
		usage
		exit 1
		;;
	esac
done

tmp_file="$(mktemp)"
trap 'rm -f "${tmp_file}"' EXIT

{
	# $schema below is a literal YAML hint, no expansion intended.
	# shellcheck disable=SC2016
	printf -- '# yaml-language-server: $schema=https://taskfile.dev/schema.json\n'
	printf -- '---\n'
	printf -- '# Code generated by scripts/generate_taskfile.sh — DO NOT EDIT.\n'
	printf -- '# Sources: taskfile/scripts/*.sh (bash-only, shebang stripped, verbatim embed).\n'
	printf -- "version: '3'\n"
} >"${tmp_file}"

script_files=()
while IFS= read -r entry; do
	[[ -n ${entry} ]] && script_files+=("${entry}")
done < <(find "${SOURCE_DIR}" -maxdepth 1 -name '*.sh' -type f | LC_ALL=C sort || true)

if [[ ${#script_files[@]} -eq 0 ]]; then
	printf -- 'tasks: {}\n' >>"${tmp_file}"
else
	printf -- 'tasks:\n' >>"${tmp_file}"
	for src in "${script_files[@]}"; do
		name="$(basename "${src}")"
		first_line="$(head -n 1 "${src}")"
		if ! [[ ${first_line} =~ ^#!.*bash ]]; then
			echo "error: ${src}: missing bash shebang (expected #!/usr/bin/env bash)" >&2
			exit 1
		fi
		body="$(tail -n +2 "${src}")"
		if [[ -z ${body//[[:space:]]/} ]]; then
			echo "error: ${src}: empty after stripping shebang" >&2
			exit 1
		fi
		{
			printf -- '  %s:\n' "${name}"
			printf -- '    internal: true\n'
			printf -- '    silent: true\n'
			printf -- '    cmd: |\n'
			awk '{ if ($0 == "") { print "" } else { printf "      %s\n", $0 } }' "${src}" | tail -n +2
		} >>"${tmp_file}"
	done
fi

# Ensure single trailing newline.
tail -c1 "${tmp_file}" | read -r _ || printf -- '\n' >>"${tmp_file}"

if [[ ${CHECK_MODE} == true ]]; then
	if [[ ! -f ${OUTPUT_FILE} ]]; then
		echo "error: ${OUTPUT_FILE#"$REPO_ROOT"/} does not exist (run without --check to generate)" >&2
		exit 1
	fi
	if ! diff -u "${OUTPUT_FILE}" "${tmp_file}"; then
		echo "error: ${OUTPUT_FILE#"$REPO_ROOT"/} is stale (run scripts/generate_taskfile.sh to regenerate)" >&2
		exit 1
	fi
	echo "taskfile-generated.yml is up to date"
else
	mkdir -p "$(dirname "${OUTPUT_FILE}")"
	mv "${tmp_file}" "${OUTPUT_FILE}"
	chmod 644 "${OUTPUT_FILE}"
	trap - EXIT
	echo "generated ${OUTPUT_FILE#"$REPO_ROOT"/}"
fi
